version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_DEV_API=http://localhost:3001
      - REACT_APP_PROD_API=http://localhost:3002
    depends_on:
      - backend_dev
      - backend_prod

  backend_dev:
    build: ./backend/dev
    ports:
      - "3001:3001"
    env_file:
      - ./backend/dev/.env

  backend_prod:
    build: ./backend/prod
    ports:
      - "3002:3002"
    env_file:
      - ./backend/prod/.env